# Generated by Django 5.1.1 on 2024-10-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='urgency_status',
            field=models.CharField(blank=True, choices=[('normal', 'Звичайне'), ('urgent', 'Терміново'), ('critical_urgent', 'Критично терміново'), ('overdue', 'Просрочене')], default='normal', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='work_status',
            field=models.CharField(blank=True, choices=[('on_inspection', 'На перевірці'), ('completed', 'Виконано'), ('in_process', 'В процесі'), ('postponed', 'Відкладено')], default='null', max_length=20, null=True),
        ),
    ]
