# Generated by Django 5.1.1 on 2024-10-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_urgency_status_alter_task_work_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='work_status',
            field=models.CharField(blank=True, choices=[('on_inspection', 'На перевірці'), ('completed', 'Виконано'), ('in_process', 'В процесі'), ('postponed', 'Відкладено'), ('free', 'Вільно')], default='free', max_length=20, null=True),
        ),
    ]
